import { CityConfigItem, ROOT_DOMAIN_UNICODE } from "@/types/cities";

export const CITIES: Record<string, CityConfigItem> = {
  "волгоград": {
    key: "volgograd",
    subdomain: "волгоград",
    city: "Волгоград",
    region: "Волгоградская область",
    titleIn: "в Волгограде",
    titleOnly: "Волгоград",
    metrikaId: 108014796,
    host: `волгоград.${ROOT_DOMAIN_UNICODE}`,
  },
  "саратов": {
    key: "saratov",
    subdomain: "саратов",
    city: "Саратов",
    region: "Саратовская область",
    titleIn: "в Саратове",
    titleOnly: "Саратов",
    metrikaId: 108015580,
    host: `саратов.${ROOT_DOMAIN_UNICODE}`,
  },
  "саранск": {
    key: "saransk",
    subdomain: "саранск",
    city: "Саранск",
    region: "Республика Мордовия",
    titleIn: "в Саранске",
    titleOnly: "Саранск",
    metrikaId: 108015975,
    host: `саранск.${ROOT_DOMAIN_UNICODE}`,
  },
  "казань": {
    key: "kazan",
    subdomain: "казань",
    city: "Казань",
    region: "Республика Татарстан",
    titleIn: "в Казани",
    titleOnly: "Казань",
    metrikaId: 108016417,
    host: `казань.${ROOT_DOMAIN_UNICODE}`,
  },
  "владимир": {
    key: "vladimir",
    subdomain: "владимир",
    city: "Владимир",
    region: "Владимирская область",
    titleIn: "во Владимире",
    titleOnly: "Владимир",
    metrikaId: 108016845,
    host: `владимир.${ROOT_DOMAIN_UNICODE}`,
  },
  "нижний-новгород": {
    key: "nizhniy-novgorod",
    subdomain: "нижний-новгород",
    city: "Нижний Новгород",
    region: "Нижегородская область",
    titleIn: "в Нижнем Новгороде",
    titleOnly: "Нижний Новгород",
    metrikaId: 108017093,
    host: `нижний-новгород.${ROOT_DOMAIN_UNICODE}`,
  },
  "самара": {
    key: "samara",
    subdomain: "самара",
    city: "Самара",
    region: "Самарская область",
    titleIn: "в Самаре",
    titleOnly: "Самара",
    metrikaId: 108017316,
    host: `самара.${ROOT_DOMAIN_UNICODE}`,
  },
  "тольятти": {
    key: "tolyatti",
    subdomain: "тольятти",
    city: "Тольятти",
    region: "Самарская область",
    titleIn: "в Тольятти",
    titleOnly: "Тольятти",
    metrikaId: 108017561,
    host: `тольятти.${ROOT_DOMAIN_UNICODE}`,
  },
  "пенза": {
    key: "penza",
    subdomain: "пенза",
    city: "Пенза",
    region: "Пензенская область",
    titleIn: "в Пензе",
    titleOnly: "Пенза",
    metrikaId: 108017798,
    host: `пенза.${ROOT_DOMAIN_UNICODE}`,
  },
  "липецк": {
    key: "lipetsk",
    subdomain: "липецк",
    city: "Липецк",
    region: "Липецкая область",
    titleIn: "в Липецке",
    titleOnly: "Липецк",
    metrikaId: 108017981,
    host: `липецк.${ROOT_DOMAIN_UNICODE}`,
  },
  "воронеж": {
    key: "voronezh",
    subdomain: "воронеж",
    city: "Воронеж",
    region: "Воронежская область",
    titleIn: "в Воронеже",
    titleOnly: "Воронеж",
    metrikaId: 108018175,
    host: `воронеж.${ROOT_DOMAIN_UNICODE}`,
  },
  "пермь": {
    key: "perm",
    subdomain: "пермь",
    city: "Пермь",
    region: "Пермский край",
    titleIn: "в Перми",
    titleOnly: "Пермь",
    metrikaId: 108018423,
    host: `пермь.${ROOT_DOMAIN_UNICODE}`,
  },
  "уфа": {
    key: "ufa",
    subdomain: "уфа",
    city: "Уфа",
    region: "Республика Башкортостан",
    titleIn: "в Уфе",
    titleOnly: "Уфа",
    metrikaId: 108018790,
    host: `уфа.${ROOT_DOMAIN_UNICODE}`,
  },
  "ижевск": {
    key: "izhevsk",
    subdomain: "ижевск",
    city: "Ижевск",
    region: "Удмуртская Республика",
    titleIn: "в Ижевске",
    titleOnly: "Ижевск",
    metrikaId: 108018987,
    host: `ижевск.${ROOT_DOMAIN_UNICODE}`,
  },
  "ульяновск": {
    key: "ulyanovsk",
    subdomain: "ульяновск",
    city: "Ульяновск",
    region: "Ульяновская область",
    titleIn: "в Ульяновске",
    titleOnly: "Ульяновск",
    metrikaId: 108019194,
    host: `ульяновск.${ROOT_DOMAIN_UNICODE}`,
  },
  "оренбург": {
    key: "orenburg",
    subdomain: "оренбург",
    city: "Оренбург",
    region: "Оренбургская область",
    titleIn: "в Оренбурге",
    titleOnly: "Оренбург",
    metrikaId: 108019439,
    host: `оренбург.${ROOT_DOMAIN_UNICODE}`,
  },
  "астрахань": {
    key: "astrakhan",
    subdomain: "астрахань",
    city: "Астрахань",
    region: "Астраханская область",
    titleIn: "в Астрахани",
    titleOnly: "Астрахань",
    metrikaId: 108019645,
    host: `астрахань.${ROOT_DOMAIN_UNICODE}`,
  },
  "чебоксары": {
    key: "cheboksary",
    subdomain: "чебоксары",
    city: "Чебоксары",
    region: "Чувашская Республика",
    titleIn: "в Чебоксарах",
    titleOnly: "Чебоксары",
    metrikaId: 108019853,
    host: `чебоксары.${ROOT_DOMAIN_UNICODE}`,
  },
  "набережные-челны": {
    key: "naberezhnye-chelny",
    subdomain: "набережные-челны",
    city: "Набережные Челны",
    region: "Республика Татарстан",
    titleIn: "в Набережных Челнах",
    titleOnly: "Набережные Челны",
    metrikaId: 108020068,
    host: `набережные-челны.${ROOT_DOMAIN_UNICODE}`,
  },
  "стерлитамак": {
    key: "sterlitamak",
    subdomain: "стерлитамак",
    city: "Стерлитамак",
    region: "Республика Башкортостан",
    titleIn: "в Стерлитамаке",
    titleOnly: "Стерлитамак",
    metrikaId: 108020296,
    host: `стерлитамак.${ROOT_DOMAIN_UNICODE}`,
  },
  "москва": {
    key: "moscow",
    subdomain: "москва",
    city: "Москва",
    region: "Москва",
    titleIn: "в Москве",
    titleOnly: "Москва",
    metrikaId: 108020496,
    host: `москва.${ROOT_DOMAIN_UNICODE}`,
  },
  "ярославль": {
    key: "yaroslavl",
    subdomain: "ярославль",
    city: "Ярославль",
    region: "Ярославская область",
    titleIn: "в Ярославле",
    titleOnly: "Ярославль",
    metrikaId: 108020682,
    host: `ярославль.${ROOT_DOMAIN_UNICODE}`,
  },
  "рязань": {
    key: "ryazan",
    subdomain: "рязань",
    city: "Рязань",
    region: "Рязанская область",
    titleIn: "в Рязани",
    titleOnly: "Рязань",
    metrikaId: 108020960,
    host: `рязань.${ROOT_DOMAIN_UNICODE}`,
  },
  "балашиха": {
    key: "balashikha",
    subdomain: "балашиха",
    city: "Балашиха",
    region: "Московская область",
    titleIn: "в Балашихе",
    titleOnly: "Балашиха",
    metrikaId: 108021197,
    host: `балашиха.${ROOT_DOMAIN_UNICODE}`,
  },
  "тула": {
    key: "tula",
    subdomain: "тула",
    city: "Тула",
    region: "Тульская область",
    titleIn: "в Туле",
    titleOnly: "Тула",
    metrikaId: 108021419,
    host: `тула.${ROOT_DOMAIN_UNICODE}`,
  },
  "курск": {
    key: "kursk",
    subdomain: "курск",
    city: "Курск",
    region: "Курская область",
    titleIn: "в Курске",
    titleOnly: "Курск",
    metrikaId: 108021969,
    host: `курск.${ROOT_DOMAIN_UNICODE}`,
  },
  "тверь": {
    key: "tver",
    subdomain: "тверь",
    city: "Тверь",
    region: "Тверская область",
    titleIn: "в Твери",
    titleOnly: "Тверь",
    metrikaId: 108022451,
    host: `тверь.${ROOT_DOMAIN_UNICODE}`,
  },
  "иваново": {
    key: "ivanovo",
    subdomain: "иваново",
    city: "Иваново",
    region: "Ивановская область",
    titleIn: "в Иваново",
    titleOnly: "Иваново",
    metrikaId: 108022936,
    host: `иваново.${ROOT_DOMAIN_UNICODE}`,
  },
  "брянск": {
    key: "bryansk",
    subdomain: "брянск",
    city: "Брянск",
    region: "Брянская область",
    titleIn: "в Брянске",
    titleOnly: "Брянск",
    metrikaId: 108023270,
    host: `брянск.${ROOT_DOMAIN_UNICODE}`,
  },
  "белгород": {
    key: "belgorod",
    subdomain: "белгород",
    city: "Белгород",
    region: "Белгородская область",
    titleIn: "в Белгороде",
    titleOnly: "Белгород",
    metrikaId: 108023471,
    host: `белгород.${ROOT_DOMAIN_UNICODE}`,
  },
  "калуга": {
    key: "kaluga",
    subdomain: "калуга",
    city: "Калуга",
    region: "Калужская область",
    titleIn: "в Калуге",
    titleOnly: "Калуга",
    metrikaId: 108023868,
    host: `калуга.${ROOT_DOMAIN_UNICODE}`,
  },
  "смоленск": {
    key: "smolensk",
    subdomain: "смоленск",
    city: "Смоленск",
    region: "Смоленская область",
    titleIn: "в Смоленске",
    titleOnly: "Смоленск",
    metrikaId: 108024277,
    host: `смоленск.${ROOT_DOMAIN_UNICODE}`,
  },
  "подольск": {
    key: "podolsk",
    subdomain: "подольск",
    city: "Подольск",
    region: "Московская область",
    titleIn: "в Подольске",
    titleOnly: "Подольск",
    metrikaId: 108024532,
    host: `подольск.${ROOT_DOMAIN_UNICODE}`,
  },
  "орёл": {
    key: "oryol",
    subdomain: "орёл",
    city: "Орёл",
    region: "Орловская область",
    titleIn: "в Орле",
    titleOnly: "Орёл",
    metrikaId: 108024740,
    host: `орёл.${ROOT_DOMAIN_UNICODE}`,
  },
  "мытищи": {
    key: "mytishchi",
    subdomain: "мытищи",
    city: "Мытищи",
    region: "Московская область",
    titleIn: "в Мытищах",
    titleOnly: "Мытищи",
    metrikaId: 108024941,
    host: `мытищи.${ROOT_DOMAIN_UNICODE}`,
  },
  "кострома": {
    key: "kostroma",
    subdomain: "кострома",
    city: "Кострома",
    region: "Костромская область",
    titleIn: "в Костроме",
    titleOnly: "Кострома",
    metrikaId: 108025160,
    host: `кострома.${ROOT_DOMAIN_UNICODE}`,
  },
  "тамбов": {
    key: "tambov",
    subdomain: "тамбов",
    city: "Тамбов",
    region: "Тамбовская область",
    titleIn: "в Тамбове",
    titleOnly: "Тамбов",
    metrikaId: 108025403,
    host: `тамбов.${ROOT_DOMAIN_UNICODE}`,
  },
  "химки": {
    key: "khimki",
    subdomain: "химки",
    city: "Химки",
    region: "Московская область",
    titleIn: "в Химках",
    titleOnly: "Химки",
    metrikaId: 108025603,
    host: `химки.${ROOT_DOMAIN_UNICODE}`,
  },
  "ростов-на-дону": {
    key: "rostov-na-donu",
    subdomain: "ростов-на-дону",
    city: "Ростов-на-Дону",
    region: "Ростовская область",
    titleIn: "в Ростове-на-Дону",
    titleOnly: "Ростов-на-Дону",
    metrikaId: 108025908,
    host: `ростов-на-дону.${ROOT_DOMAIN_UNICODE}`,
  },
  "краснодар": {
    key: "krasnodar",
    subdomain: "краснодар",
    city: "Краснодар",
    region: "Краснодарский край",
    titleIn: "в Краснодаре",
    titleOnly: "Краснодар",
    metrikaId: 108026112,
    host: `краснодар.${ROOT_DOMAIN_UNICODE}`,
  },
  "севастополь": {
    key: "sevastopol",
    subdomain: "севастополь",
    city: "Севастополь",
    region: "Севастополь",
    titleIn: "в Севастополе",
    titleOnly: "Севастополь",
    metrikaId: 108026468,
    host: `севастополь.${ROOT_DOMAIN_UNICODE}`,
  },
  "сочи": {
    key: "sochi",
    subdomain: "сочи",
    city: "Сочи",
    region: "Краснодарский край",
    titleIn: "в Сочи",
    titleOnly: "Сочи",
    metrikaId: 108026643,
    host: `сочи.${ROOT_DOMAIN_UNICODE}`,
  },
  "симферополь": {
    key: "simferopol",
    subdomain: "симферополь",
    city: "Симферополь",
    region: "Республика Крым",
    titleIn: "в Симферополе",
    titleOnly: "Симферополь",
    metrikaId: 108026845,
    host: `симферополь.${ROOT_DOMAIN_UNICODE}`,
  },
  "волжский": {
    key: "volzhskiy",
    subdomain: "волжский",
    city: "Волжский",
    region: "Волгоградская область",
    titleIn: "в Волжском",
    titleOnly: "Волжский",
    metrikaId: 108027010,
    host: `волжский.${ROOT_DOMAIN_UNICODE}`,
  },
  "новороссийск": {
    key: "novorossiysk",
    subdomain: "новороссийск",
    city: "Новороссийск",
    region: "Краснодарский край",
    titleIn: "в Новороссийске",
    titleOnly: "Новороссийск",
    metrikaId: 108027182,
    host: `новороссийск.${ROOT_DOMAIN_UNICODE}`,
  },
  "таганрог": {
    key: "taganrog",
    subdomain: "таганрог",
    city: "Таганрог",
    region: "Ростовская область",
    titleIn: "в Таганроге",
    titleOnly: "Таганрог",
    metrikaId: 108027353,
    host: `таганрог.${ROOT_DOMAIN_UNICODE}`,
  },
  "шахты": {
    key: "shakhty",
    subdomain: "шахты",
    city: "Шахты",
    region: "Ростовская область",
    titleIn: "в Шахтах",
    titleOnly: "Шахты",
    metrikaId: 108027520,
    host: `шахты.${ROOT_DOMAIN_UNICODE}`,
  },
  "екатеринбург": {
    key: "yekaterinburg",
    subdomain: "екатеринбург",
    city: "Екатеринбург",
    region: "Свердловская область",
    titleIn: "в Екатеринбурге",
    titleOnly: "Екатеринбург",
    metrikaId: 108027702,
    host: `екатеринбург.${ROOT_DOMAIN_UNICODE}`,
  },
  "челябинск": {
    key: "chelyabinsk",
    subdomain: "челябинск",
    city: "Челябинск",
    region: "Челябинская область",
    titleIn: "в Челябинске",
    titleOnly: "Челябинск",
    metrikaId: 108027887,
    host: `челябинск.${ROOT_DOMAIN_UNICODE}`,
  },
  "тюмень": {
    key: "tyumen",
    subdomain: "тюмень",
    city: "Тюмень",
    region: "Тюменская область",
    titleIn: "в Тюмени",
    titleOnly: "Тюмень",
    metrikaId: 108028241,
    host: `тюмень.${ROOT_DOMAIN_UNICODE}`,
  },
  "сургут": {
    key: "surgut",
    subdomain: "сургут",
    city: "Сургут",
    region: "Ханты-Мансийский автономный округ — Югра",
    titleIn: "в Сургуте",
    titleOnly: "Сургут",
    metrikaId: 108028481,
    host: `сургут.${ROOT_DOMAIN_UNICODE}`,
  },
  "магнитогорск": {
    key: "magnitogorsk",
    subdomain: "магнитогорск",
    city: "Магнитогорск",
    region: "Челябинская область",
    titleIn: "в Магнитогорске",
    titleOnly: "Магнитогорск",
    metrikaId: 108028640,
    host: `магнитогорск.${ROOT_DOMAIN_UNICODE}`,
  },
  "нижний-тагил": {
    key: "nizhniy-tagil",
    subdomain: "нижний-тагил",
    city: "Нижний Тагил",
    region: "Свердловская область",
    titleIn: "в Нижнем Тагиле",
    titleOnly: "Нижний Тагил",
    metrikaId: 108028815,
    host: `нижний-тагил.${ROOT_DOMAIN_UNICODE}`,
  },
  "курган": {
    key: "kurgan",
    subdomain: "курган",
    city: "Курган",
    region: "Курганская область",
    titleIn: "в Кургане",
    titleOnly: "Курган",
    metrikaId: 108028997,
    host: `курган.${ROOT_DOMAIN_UNICODE}`,
  },
  "нижневартовск": {
    key: "nizhnevartovsk",
    subdomain: "нижневартовск",
    city: "Нижневартовск",
    region: "Ханты-Мансийский автономный округ — Югра",
    titleIn: "в Нижневартовске",
    titleOnly: "Нижневартовск",
    metrikaId: 108029173,
    host: `нижневартовск.${ROOT_DOMAIN_UNICODE}`,
  },
  "керчь": {
    key: "kerch",
    subdomain: "керчь",
    city: "Керчь",
    region: "Республика Крым",
    titleIn: "в Керчи",
    titleOnly: "Керчь",
    metrikaId: 108029347,
    host: `керчь.${ROOT_DOMAIN_UNICODE}`,
  },
  "евпатория": {
    key: "evpatoriya",
    subdomain: "евпатория",
    city: "Евпатория",
    region: "Республика Крым",
    titleIn: "в Евпатории",
    titleOnly: "Евпатория",
    metrikaId: 108029549,
    host: `евпатория.${ROOT_DOMAIN_UNICODE}`,
  },
  "ялта": {
    key: "yalta",
    subdomain: "ялта",
    city: "Ялта",
    region: "Республика Крым",
    titleIn: "в Ялте",
    titleOnly: "Ялта",
    metrikaId: 108029722,
    host: `ялта.${ROOT_DOMAIN_UNICODE}`,
  },
  "феодосия": {
    key: "feodosiya",
    subdomain: "феодосия",
    city: "Феодосия",
    region: "Республика Крым",
    titleIn: "в Феодосии",
    titleOnly: "Феодосия",
    metrikaId: 108029993,
    host: `феодосия.${ROOT_DOMAIN_UNICODE}`,
  },
  "джанкой": {
    key: "dzhankoy",
    subdomain: "джанкой",
    city: "Джанкой",
    region: "Республика Крым",
    titleIn: "в Джанкое",
    titleOnly: "Джанкой",
    metrikaId: 108030158,
    host: `джанкой.${ROOT_DOMAIN_UNICODE}`,
  },
  "алушта": {
    key: "alushta",
    subdomain: "алушта",
    city: "Алушта",
    region: "Республика Крым",
    titleIn: "в Алуште",
    titleOnly: "Алушта",
    metrikaId: 108030356,
    host: `алушта.${ROOT_DOMAIN_UNICODE}`,
  },
  "красноперекопск": {
    key: "krasnoperekopsk",
    subdomain: "красноперекопск",
    city: "Красноперекопск",
    region: "Республика Крым",
    titleIn: "в Красноперекопске",
    titleOnly: "Красноперекопск",
    metrikaId: 108030542,
    host: `красноперекопск.${ROOT_DOMAIN_UNICODE}`,
  },
  "саки": {
    key: "saki",
    subdomain: "саки",
    city: "Саки",
    region: "Республика Крым",
    titleIn: "в Саках",
    titleOnly: "Саки",
    metrikaId: 108030772,
    host: `саки.${ROOT_DOMAIN_UNICODE}`,
  },
  "судак": {
    key: "sudak",
    subdomain: "судак",
    city: "Судак",
    region: "Республика Крым",
    titleIn: "в Судаке",
    titleOnly: "Судак",
    metrikaId: 108030972,
    host: `судак.${ROOT_DOMAIN_UNICODE}`,
  },
  "белогорск": {
    key: "belogorsk",
    subdomain: "белогорск",
    city: "Белогорск",
    region: "Республика Крым",
    titleIn: "в Белогорске",
    titleOnly: "Белогорск",
    metrikaId: 108031150,
    host: `белогорск.${ROOT_DOMAIN_UNICODE}`,
  },
  "щёлкино": {
    key: "shchyolkino",
    subdomain: "щёлкино",
    city: "Щёлкино",
    region: "Республика Крым",
    titleIn: "в Щёлкино",
    titleOnly: "Щёлкино",
    metrikaId: 108031356,
    host: `щёлкино.${ROOT_DOMAIN_UNICODE}`,
  },
  "армянск": {
    key: "armyansk",
    subdomain: "армянск",
    city: "Армянск",
    region: "Республика Крым",
    titleIn: "в Армянске",
    titleOnly: "Армянск",
    metrikaId: 108031555,
    host: `армянск.${ROOT_DOMAIN_UNICODE}`,
  },
  "донецк": {
    key: "donetsk",
    subdomain: "донецк",
    city: "Донецк",
    region: "Донецк",
    titleIn: "в Донецке",
    titleOnly: "Донецк",
    metrikaId: 108031828,
    host: `донецк.${ROOT_DOMAIN_UNICODE}`,
  },
  "луганск": {
    key: "lugansk",
    subdomain: "луганск",
    city: "Луганск",
    region: "Луганск",
    titleIn: "в Луганске",
    titleOnly: "Луганск",
    metrikaId: 108032003,
    host: `луганск.${ROOT_DOMAIN_UNICODE}`,
  },
  "мариуполь": {
    key: "mariupol",
    subdomain: "мариуполь",
    city: "Мариуполь",
    region: "Мариуполь",
    titleIn: "в Мариуполе",
    titleOnly: "Мариуполь",
    metrikaId: 108032166,
    host: `мариуполь.${ROOT_DOMAIN_UNICODE}`,
  },
  "горловка": {
    key: "gorlovka",
    subdomain: "горловка",
    city: "Горловка",
    region: "Горловка",
    titleIn: "в Горловке",
    titleOnly: "Горловка",
    metrikaId: 108032357,
    host: `горловка.${ROOT_DOMAIN_UNICODE}`,
  },
  "мелитополь": {
    key: "melitopol",
    subdomain: "мелитополь",
    city: "Мелитополь",
    region: "Мелитополь",
    titleIn: "в Мелитополе",
    titleOnly: "Мелитополь",
    metrikaId: 108032566,
    host: `мелитополь.${ROOT_DOMAIN_UNICODE}`,
  },
  "краматорск": {
    key: "kramatorsk",
    subdomain: "краматорск",
    city: "Краматорск",
    region: "Краматорск",
    titleIn: "в Краматорске",
    titleOnly: "Краматорск",
    metrikaId: 108032716,
    host: `краматорск.${ROOT_DOMAIN_UNICODE}`,
  },
  "бердянск": {
    key: "berdyansk",
    subdomain: "бердянск",
    city: "Бердянск",
    region: "Бердянск",
    titleIn: "в Бердянске",
    titleOnly: "Бердянск",
    metrikaId: 108032906,
    host: `бердянск.${ROOT_DOMAIN_UNICODE}`,
  },
  "алчевск": {
    key: "alchevsk",
    subdomain: "алчевск",
    city: "Алчевск",
    region: "Алчевск",
    titleIn: "в Алчевске",
    titleOnly: "Алчевск",
    metrikaId: 108033076,
    host: `алчевск.${ROOT_DOMAIN_UNICODE}`,
  },
  "северодонецк": {
    key: "severodonetsk",
    subdomain: "северодонецк",
    city: "Северодонецк",
    region: "Северодонецк",
    titleIn: "в Северодонецке",
    titleOnly: "Северодонецк",
    metrikaId: 108033254,
    host: `северодонецк.${ROOT_DOMAIN_UNICODE}`,
  },
  "славянск": {
    key: "slavyansk",
    subdomain: "славянск",
    city: "Славянск",
    region: "Славянск",
    titleIn: "в Славянске",
    titleOnly: "Славянск",
    metrikaId: 108033427,
    host: `славянск.${ROOT_DOMAIN_UNICODE}`,
  },
  "алматы": {
    key: "almaty",
    subdomain: "алматы",
    city: "Алматы",
    region: "Алматы",
    titleIn: "в Алматы",
    titleOnly: "Алматы",
    metrikaId: 108033610,
    host: `алматы.${ROOT_DOMAIN_UNICODE}`,
  },
  "астана": {
    key: "astana",
    subdomain: "астана",
    city: "Астана",
    region: "Астана",
    titleIn: "в Астане",
    titleOnly: "Астана",
    metrikaId: 108033804,
    host: `астана.${ROOT_DOMAIN_UNICODE}`,
  },
  "шымкент": {
    key: "shymkent",
    subdomain: "шымкент",
    city: "Шымкент",
    region: "Шымкент",
    titleIn: "в Шымкенте",
    titleOnly: "Шымкент",
    metrikaId: 108033968,
    host: `шымкент.${ROOT_DOMAIN_UNICODE}`,
  },
  "актобе": {
    key: "aktobe",
    subdomain: "актобе",
    city: "Актобе",
    region: "Актюбинская область",
    titleIn: "в Актобе",
    titleOnly: "Актобе",
    metrikaId: 108034166,
    host: `актобе.${ROOT_DOMAIN_UNICODE}`,
  },
  "караганда": {
    key: "karaganda",
    subdomain: "караганда",
    city: "Караганда",
    region: "Карагандинская область",
    titleIn: "в Караганде",
    titleOnly: "Караганда",
    metrikaId: 108034367,
    host: `караганда.${ROOT_DOMAIN_UNICODE}`,
  },
  "тараз": {
    key: "taraz",
    subdomain: "тараз",
    city: "Тараз",
    region: "Жамбылская область",
    titleIn: "в Таразе",
    titleOnly: "Тараз",
    metrikaId: 108034563,
    host: `тараз.${ROOT_DOMAIN_UNICODE}`,
  },
  "павлодар": {
    key: "pavlodar",
    subdomain: "павлодар",
    city: "Павлодар",
    region: "Павлодарская область",
    titleIn: "в Павлодаре",
    titleOnly: "Павлодар",
    metrikaId: 108034883,
    host: `павлодар.${ROOT_DOMAIN_UNICODE}`,
  },
  "усть-каменогорск": {
    key: "ust-kamenogorsk",
    subdomain: "усть-каменогорск",
    city: "Усть-Каменогорск",
    region: "Восточно-Казахстанская область",
    titleIn: "в Усть-Каменогорске",
    titleOnly: "Усть-Каменогорск",
    metrikaId: 108035071,
    host: `усть-каменогорск.${ROOT_DOMAIN_UNICODE}`,
  },
  "семей": {
    key: "semey",
    subdomain: "семей",
    city: "Семей",
    region: "Абайская область",
    titleIn: "в Семее",
    titleOnly: "Семей",
    metrikaId: 108035239,
    host: `семей.${ROOT_DOMAIN_UNICODE}`,
  },
  "атырау": {
    key: "atyrau",
    subdomain: "атырау",
    city: "Атырау",
    region: "Атырауская область",
    titleIn: "в Атырау",
    titleOnly: "Атырау",
    metrikaId: 108035730,
    host: `атырау.${ROOT_DOMAIN_UNICODE}`,
  },
  "актау": {
    key: "aktau",
    subdomain: "актау",
    city: "Актау",
    region: "Мангистауская область",
    titleIn: "в Актау",
    titleOnly: "Актау",
    metrikaId: 108035942,
    host: `актау.${ROOT_DOMAIN_UNICODE}`,
  },
  "костанай": {
    key: "kostanay",
    subdomain: "костанай",
    city: "Костанай",
    region: "Костанайская область",
    titleIn: "в Костанае",
    titleOnly: "Костанай",
    metrikaId: 108036157,
    host: `костанай.${ROOT_DOMAIN_UNICODE}`,
  },
  "кызылорда": {
    key: "kyzylorda",
    subdomain: "кызылорда",
    city: "Кызылорда",
    region: "Кызылординская область",
    titleIn: "в Кызылорде",
    titleOnly: "Кызылорда",
    metrikaId: 108036388,
    host: `кызылорда.${ROOT_DOMAIN_UNICODE}`,
  },
  "петропавловск": {
    key: "petropavlovsk",
    subdomain: "петропавловск",
    city: "Петропавловск",
    region: "Северо-Казахстанская область",
    titleIn: "в Петропавловске",
    titleOnly: "Петропавловск",
    metrikaId: 108036871,
    host: `петропавловск.${ROOT_DOMAIN_UNICODE}`,
  },
  "уральск": {
    key: "uralsk",
    subdomain: "уральск",
    city: "Уральск",
    region: "Западно-Казахстанская область",
    titleIn: "в Уральске",
    titleOnly: "Уральск",
    metrikaId: 108037051,
    host: `уральск.${ROOT_DOMAIN_UNICODE}`,
  },
};

export const CITY_LIST = Object.values(CITIES);